version: "3.7"

services:
  pg_learn:
    image: postgres:9.6
    container_name: test_DB
    hostname: test
    ports:
      - "8432:5432"
    expose:
      - 8432
    environment:
      POSTGRES_USER: 'avp'
      POSTGRES_PASSWORD: 'avp'
      POSTGRES_DB: 'test_DB'
